{% set name = "eip712" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ApeWorX/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 949aa31d38911ed5b5cb31b43783ba5764c09a3d0a23bfee5e18259b550d1751

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}


requirements:
  host:
    - python {{ python_min }}
    - setuptools >=51.1.1
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - dataclassy >=0.8.2,<1
    - eth-abi >=5.1.0,<6
    - eth-account >=0.10.0,<0.12
    - eth-hash
    - eth-typing >=3.3.0,<4
    - eth-utils >=2.1.0,<3
    - hexbytes >=0.3.0,<1

test:
  imports:
    - eip712
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests
  requires:
    - hypothesis
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/ApeWorX/eip712
  summary: 'eip712: Message classes for typed structured data hashing and signing in Ethereum'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
